CREATE TABLE limits
(
    id                       BIGSERIAL PRIMARY KEY,
    limit_sum                DECIMAL(19, 4),
    limit_remains            DECIMAL(19, 4),
    limit_datetime           TIMESTAMP WITH TIME ZONE,
    limit_currency_shortname VARCHAR(3),
    status                   VARCHAR(255) NOT NULL DEFAULT 'ACTIVE'
);

-- Comments for the 'limits' table
COMMENT ON TABLE limits IS 'Stores information about spending limits for various categories or accounts, including the maximum allowable amounts, the currency of these amounts, and the timestamp of when these limits were set or last updated.';

-- Comments for columns in the 'limits' table
COMMENT ON COLUMN limits.id IS 'A unique identifier for each limit entry, automatically generated by the database.';
COMMENT ON COLUMN limits.limit_sum IS 'The maximum spending amount allowed for a particular limit, stored as a decimal value to accommodate precise financial figures.';
COMMENT ON COLUMN limits.limit_datetime IS 'The date and time when the limit was set or last updated, including the time zone to ensure time consistency across different geographic locations.';
COMMENT ON COLUMN limits.limit_currency_shortname IS 'The ISO 4217 currency code that specifies the currency of the limit amount, ensuring financial operations are handled in the correct currency.';
